#!/bin/gawk -f

# Copyright (C) 2003 Jeremy Booth (jeremy@newdawnsoftware.com)
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this 
# list of conditions and the following disclaimer. Redistributions in binary 
# form must reproduce the above copyright notice, this list of conditions and 
# the following disclaimer in the documentation and/or other materials provided
# with the distribution. 
# The name of the author may not be used to endorse or promote products derived
# from this software without specific prior written permission. 
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE

NR == 1 { 
  FILENAME == ARGV[1];
  printf("package net.java.games.input;\n\n")
  printf("\n");
  printf("/**\n * This file is generated from %s please do not edit\n */\n", FILENAME);
  printf("class NativeDefinitions {\n")
}
/#define ABS_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define REL_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define BTN_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define KEY_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define BUS_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define EV_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define FF_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
/#define USAGE_/ { 
  printf("    public static final int %s = %s;\n", $2, $3) 
}
END {
  printf("}\n");
}
