/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_LinuxDeviceRumbler */

#ifndef _Included_net_java_games_input_LinuxDeviceRumbler
#define _Included_net_java_games_input_LinuxDeviceRumbler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_LinuxDeviceRumbler
 * Method:    nativeRumble
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxDeviceRumbler_nativeRumble
  (JNIEnv *, jobject, jint, jfloat);
#ifdef __cplusplus
}
#endif
#endif
