/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_LinuxEnvironmentPlugin */

#ifndef _Included_net_java_games_input_LinuxEnvironmentPlugin
#define _Included_net_java_games_input_LinuxEnvironmentPlugin
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: defaultEnvironment */
/* Inaccessible static: class_00024net_00024java_00024games_00024input_00024ControllerEnvironment */
/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_getDeviceName
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    getNumAbsAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_getNumAbsAxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    getNumRelAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_getNumRelAxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    getNumButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_getNumButtons
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_init
  (JNIEnv *, jobject);

/*
 * Class:     net_java_games_input_LinuxEnvironmentPlugin
 * Method:    getNumberOfDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEnvironmentPlugin_getNumberOfDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
