/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_LinuxKeyboard */

#ifndef _Included_net_java_games_input_LinuxKeyboard
#define _Included_net_java_games_input_LinuxKeyboard
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: NO_AXES */
/* Inaccessible static: NO_CONTROLLERS */
/* Inaccessible static: NO_RUMBLERS */
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: class_00024net_00024java_00024games_00024input_00024Keyboard */
/*
 * Class:     net_java_games_input_LinuxKeyboard
 * Method:    getNativeSupportedButtons
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxKeyboard_getNativeSupportedButtons
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     net_java_games_input_LinuxKeyboard
 * Method:    nativePoll
 * Signature: (I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxKeyboard_nativePoll
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray);

/*
 * Class:     net_java_games_input_LinuxKeyboard
 * Method:    getNativePortType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxKeyboard_getNativePortType
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
