/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_JInputLibrary */

#ifndef _Included_net_java_games_input_JInputLibrary
#define _Included_net_java_games_input_JInputLibrary
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: inited */
/* Inaccessible static: workerThreadMonitor */
/* Inaccessible static: shutdown */
/* Inaccessible static: shutdownThreadMonitor */
/* Inaccessible static: cleanupDone */
/* Inaccessible static: rumbler */
/* Inaccessible static: force */
/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_JInputLibrary_getDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getNumAbsAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getNumAbsAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getNumRelAxes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getNumRelAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getNumButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getNumButtons
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getNumberOfDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getNumberOfDevices
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getSupportedAbsAxes
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_JInputLibrary_getSupportedAbsAxes
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getSupportedRelAxes
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_JInputLibrary_getSupportedRelAxes
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getSupportedButtons
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_JInputLibrary_getSupportedButtons
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    poll
 * Signature: (I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_poll
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getAbsAxisFuzz
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getAbsAxisFuzz
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getAbsAxisMaximum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getAbsAxisMaximum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getAbsAxisMinimum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getAbsAxisMinimum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getNativePortType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_JInputLibrary_getNativePortType
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    getFFEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_input_JInputLibrary_getFFEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    nativeRumble
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_JInputLibrary_nativeRumble
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_java_games_input_JInputLibrary
 * Method:    nativeCleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_JInputLibrary_nativeCleanup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
